### ISSUE TITLE
Configure Terraform to talk to the remote state store...

### ISSUE THREAD

**Issue by locactus** [datawire/reference-infrastructure-fabric#4]
Hi,

Gong through your steps to setup Kubernetes in AWS and having problems with 7. Generate the AWS networking environment.

Looks like the remote command has been removed from the latest version of Terraform. Could you please suggest a version I should be using?

239:reference-infrastructure-fabric ossiejam$ terraform --help remote

Thanks in advance.

**Comment by plombardi89** [comment]
Hi @locactus ... this works with 0.9.3. This repository needs a refresh. Sorry for the issue.

**Comment by locactus** [comment]
@plombardi89 Thanks for the prompt reply I'll give it go.

**Comment by locactus** [comment]
Hi @plombardi89 gave it a go but didn't work. For the scripts to work for me I had to revert to version Terraform v0.8.8 as remote was removed after this.

Thanks.

**Comment by plombardi89** [comment]
@locactus Thanks for the info. I'm gonna update the doc with that as a stop gap to redoing this guide.

**Comment by locactus** [comment]
@plombardi89 Its only for that step as:

8.3 Plan and Apply the Kubernetes cluster with Terraform

3 Run terraform get -update=true

This required v0.9.3+

I switched back to 0.9.3. at that point and completed the rest of the steps. 

BTW Great job all works fine!! Your scripts really helped me out 👍
